In [2]:
import numpy as np
import matplotlib.pyplot as plt

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [5]:
a.dtype

dtype('int64')

In [7]:
float_arr = np.array([1, 4, 9, 16], dtype=np.float64)
float_arr

array([  1.,   4.,   9.,  16.])

In [8]:
float_arr.size, float_arr.shape, float_arr.ndim

(4, (4,), 1)

In [12]:
two_dim = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float64)
two_dim
two_dim.size, two_dim.shape, two_dim.ndim

(6, (2, 3), 2)

In [15]:
np.zeros((4,4), 'd')

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [16]:
np.empty((3, 3), 'd')

array([[ -2.00000000e+000,  -2.00000000e+000,   5.92878775e-323],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000]])

In [18]:
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [19]:
np.linspace(0, 12, 4)

array([  0.,   4.,   8.,  12.])

In [20]:
np.linspace(0, 12, 5)

array([  0.,   3.,   6.,   9.,  12.])

In [21]:
np.linspace(0, 12, 7)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.])

In [27]:
first_arr = np.random.standard_normal([4, 3])

In [28]:
second_arr = np.random.standard_normal([4, 3])

In [29]:
np.vstack([first_arr, second_arr])

array([[ 0.70147709, -1.46848419,  1.38179985],
       [-1.26422602, -0.88125865,  0.04631896],
       [ 0.501663  ,  1.71154334,  0.24491036],
       [ 0.10443039,  0.82344891,  0.38447966],
       [ 0.15636591,  0.50501738, -0.79214295],
       [ 1.41657865, -1.00405055, -0.90147659],
       [ 0.6166644 ,  0.07073681, -2.52552296],
       [ 0.70978038, -0.61811139, -0.53663174]])

In [30]:
np.hstack([first_arr, second_arr])

array([[ 0.70147709, -1.46848419,  1.38179985,  0.15636591,  0.50501738,
        -0.79214295],
       [-1.26422602, -0.88125865,  0.04631896,  1.41657865, -1.00405055,
        -0.90147659],
       [ 0.501663  ,  1.71154334,  0.24491036,  0.6166644 ,  0.07073681,
        -2.52552296],
       [ 0.10443039,  0.82344891,  0.38447966,  0.70978038, -0.61811139,
        -0.53663174]])

In [31]:
first_arr.transpose()

array([[ 0.70147709, -1.26422602,  0.501663  ,  0.10443039],
       [-1.46848419, -0.88125865,  1.71154334,  0.82344891],
       [ 1.38179985,  0.04631896,  0.24491036,  0.38447966]])

In [32]:
np.save('first_arr.npy', first_arr)

In [33]:
loaded_first_arr = np.load('first_arr.npy')
loaded_first_arr

array([[ 0.70147709, -1.46848419,  1.38179985],
       [-1.26422602, -0.88125865,  0.04631896],
       [ 0.501663  ,  1.71154334,  0.24491036],
       [ 0.10443039,  0.82344891,  0.38447966]])